spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
     name: microservicecloud-config-atguitu-dev
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-atguitu-test
#请保存为UTF-8格式